### ISSUE TITLE
Missing `/assets/main.css' not found - happens intermittently

### ISSUE THREAD

**Issue by gwood** [pages-themes/tactile#6]
Following the process for https://github.com/pages-themes/tactile#previewing-the-theme-locally

I got a **`Missing '/assets/main.css' not found`** error. _Each full path was abbreviated below._
N.B.: This error does not always occur when I browse the demo files.

```bash
Configuration file: /Users/support/jekyll/tactile/_config.yml
            Source: /Users/support/jekyll/tactile
       Destination: /Users/support/jekyll/tactile/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.408 seconds.
 Auto-regeneration: enabled for '/Users/support/jekyll/tactile'
    Server address: http://127.0.0.1:4000
  Server running... press ctrl-c to stop.
[2017-12-26 16:29:40] ERROR `/assets/main.css' not found.
```

**Comment by benbalter** [comment]
@gwood have you modified the theme at all? There is no reference to `/assets/main.css' in the default theme.

**Comment by gwood** [comment]
@benbalter 

I have just attempted to install the theme into Jekyll.
Multiple attempts have failed.  I am not sure of the proper process to bind the Theme to Jekyll.
Do you have a process for taking the Jekyll installation instructions
and step by step installing the theme, that works on a Mac OS X host?  I would be very grateful for a step-by-step process.

Here is one of the many step by step process that failed for me. As a new user of Jekyll, my process is probably incorrect.  Please correct any mis-steps below if you can find them

I have posted the original error - using just this repo, to test and fail.

I have gotten the gem to work - sort of - but the pages will not render at all, and a GitHub repository needed to be named in the config YAML file, and that messed up the posts from rendering.

Regards,
George Wood

# Setup Jekyll 2017-12-26 Tue 15:41:52-0600

[Jekyll Quickstart](https://jekyllrb.com/docs/quickstart/)

## Themes

Found a Theme that I liked: [Tactile](https://github.com/pages-themes/tactile#usage)

## This is an article on how to use the new Theme:
[Understanding GEM based Themes](https://jekyllrb.com/docs/themes/#understanding-gem-based-themes)

The Static Site Generated by Jekyll
```bash
cd myBlog
```

Recipe for creating myBlog
```bash
# Install Jekyll and Bundler gems through RubyGems
gem install jekyll bundler

# Create a new Jekyll site at ./myBlog
jekyll new myBlog

# Change into your new directory
cd myBlog

# Build the site on the preview server
bundle exec jekyll serve

# Now browse to http://localhost:4000
```

## Jekyll errors

_config.yaml
```bash
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
```

Gemfile
```bash
source "https://rubygems.org"

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
#gem "jekyll", "~> 3.6.2"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
#gem "minima", "~> 2.0"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

Errors with Jekyl on changing themes :bundle update github-pages
```bash
$ bundle update github-pages
Running `bundle update github-pages` with bundler 1.16.1
Could not find gem 'github-pages'.
Bundler::GemNotFound: Could not find gem 'github-pages'.
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/common.rb:77:in `block in ensure_all_gems_in_lockfile!'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/common.rb:76:in `each'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/common.rb:76:in `ensure_all_gems_in_lockfile!'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/update.rb:38:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:266:in `update'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'
$ bundle install github-pages
Running `bundle install github-pages` with bundler 1.16.1
ERROR: "bundle install" was called with arguments ["github-pages"]
Usage: "bundle install [OPTIONS]"
$ 
```

**Comment by gwood** [comment]
The error that prompted the ticket is below.  This was just attempting to get the original 

```bash
support/jekyll $ git clone https://github.com/pages-themes/tactile
Cloning into 'tactile'...
remote: Counting objects: 215, done.        
remote: Total 215 (delta 0), reused 0 (delta 0), pack-reused 215        
Receiving objects: 100% (215/215), 83.22 KiB | 202.00 KiB/s, done.
Resolving deltas: 100% (97/97), done.
$ cd tactile/
$ script/bootstrap
Successfully installed bundler-1.16.1
Parsing documentation for bundler-1.16.1
Done installing documentation for bundler after 5 seconds
1 gem installed
Running `bundle install` with bundler 1.16.1
Found changes from the lockfile, re-resolving dependencies because the list of sources changed, \
the dependencies in your gemfile changed, you added a new platform to your gemfile, the \

gemspecs for path gems changed
HTTP GET https://index.rubygems.org/versions
HTTP 206 Partial Content https://index.rubygems.org/versions
Fetching gem metadata from https://rubygems.org/
Looking up gems ["jekyll", "jekyll-seo-tag"]
Looking up gems ["classifier", "directory_watcher", "hoe", "liquid", "maruku", "open4", \
"RedCloth", "rdiscount", "albino", "kramdown", "pygments.rb", "commander", \
"safe_yaml", "colorator", "redcarpet", "listen", "toml", "jekyll-coffeescript", \
"mercenary", "sass", "jekyll-sass-converter", "jekyll-gist", "jekyll-paginate", \
"jekyll-watch", "classifier-reborn", "rouge", "pathutil", "addressable"]
Looking up gems ["stemmer", "fast-stemmer", "syntax", "rubypython", \
"posix-spawn", "yajl-ruby", "multi_json", "parslet", "coffee-script", \
"coffee-script-source", "rake", "rubyforge", "RubyInline", "gemcutter", \
"echoe", "highline", "bones", "rb-fchange", "rb-fsevent", "rb-inotify", \
"rb-kqueue", "celluloid", "celluloid-io", "ruby_dep", "sass-listen", \
"octokit", "psych", "forwardable-extended", "thor", "launchy", "rspec", "public_suffix"]
Looking up gems ["blankslate", "ffi", "json", "net-scp", "json_pure", "termios", "faraday", "faraday_middleware", "hashie", "multi_xml", "rash", "netrc", "sawyer", "rcov", "allison", "rdoc", \
"little-plugger", "loquacious", "bones-extras", "bones-git", "execjs", "configuration", "spoon", \
"jar-dependencies", "cucumber", "diff-lcs", "spicycode-rcov", "rspec-core", "rspec-expectations",\
 "rspec-mocks", "nio4r", "bundler", "dotenv", "nenv", "rspec-logsplit", "timers", "facter", \
"celluloid-essentials", "celluloid-extras", "celluloid-fsm", "celluloid-pool", "celluloid-supervision", \
"ZenTest", "win32-api"]
Looking up gems ["minitest", "bones-rcov", "bones-rspec", "bones-rubyforge",\
"bones-zentest", "git", "oauth2", "roauth", "ruby-maven", "dotenv-deployment", \
"spruz", "rack", "multipart-post", "rspec-support", "builder", "polyglot", "term-ansicolor", \
"treetop", "gherkin", "multi_test", "cucumber-core", "gherkin3", "cucumber-wire", \
"event-bus", "cucumber-expressions", "celluloid-gems", "net-ssh", "coveralls", \
"rubocop", "uri_template", "test-unit", "CFPropertyList", "sys-admin", "win32console", \
"win32-dir", "windows-api", "windows-pr", "win32-security", "hitimes"]
HTTP GET https://index.rubygems.org/info/treetop
HTTP 206 Partial Content https://index.rubygems.org/info/treetop
Looking up gems ["tins", "maven-tools", "ruby-maven-libs", "backports", \
"cucumber-tag_expressions", "camping", "fcgi", "memcache-client", \
"mongrel", "ruby-openid", "test-spec", "thin", "trollop", "needle", "jruby-pageant", \
"bcrypt_pbkdf", "rbnacl", "rbnacl-libsodium", "libxml-ruby", "power_assert", \
"ffi-win32-extensions", "mkrf", "rake-compiler", "faraday-middleware", \
"httpauth", "jwt", "colorize", "rest-client", "simplecov", "rainbow", "parser", \
"powerpack", "ruby-progressbar", "astrolabe", "unicode-display_width", \
"parallel", "facets"]
Looking up gems ["virtus", "cgi_multipart_eof_fix", "daemons", "fastthread", \
"gem_plugin", "activesupport", "markaby", "metaid", "activerecord", "mab", \
"ruby-yadis", "curses", "flexmock", "mocha", "sexp_processor", "ast", "slop", \
"eventmachine", "eventmachine-le", "http_parser.rb", "preforker", "pattern-match", \
"simplecov-html", "docile", "lockfile", "mime-types", "http-cookie", "http-accept"]
Looking up gems ["i18n", "tzinfo", "thread_safe", "concurrent-ruby", \
"method_source", "descendants_tracker", "axiom-types", "coercible", \
"equalizer", "domain_name", "sqlite3", "metaclass", "archive-tar-minitar", \
"nokogiri", "mime-types-data", "activemodel", "arel", "activerecord-deprecated_finders"]
Looking up gems ["adamantium", "ice_nine", "atomic", "functional-ruby", \
"ref", "ruby_parser", "unf", "racc", "rexical", "tenderlove-frex", "weakling",\
 "mini_portile", "mini_portile2", "pkg-config", "bcrypt-ruby", "minitar", "minitar-cli"]
Looking up gems ["ParseTree", "memoizable", "bcrypt", "unf_ext", "powerbar"]
Looking up gems ["ansi", "SexpProcessor"]
Double checking for ["bundler"] in rubygems repository https://rubygems.org/ or installed locally
Fetching gem metadata from https://rubygems.org/
Looking up gems ["bundler"]
Resolving dependencies...
Using public_suffix 3.0.1
0:  public_suffix (3.0.1) from /usr/local/lib/ruby/gems/2.4.0/specifications/public_suffix-3.0.1.gemspec
Using addressable 2.5.2
0:  addressable (2.5.2) from /usr/local/lib/ruby/gems/2.4.0/specifications/addressable-2.5.2.gemspec
Using bundler 1.16.1
0:  bundler (1.16.1) from /usr/local/lib/ruby/gems/2.4.0/specifications/bundler-1.16.1.gemspec
Using colorator 1.1.0
0:  colorator (1.1.0) from /usr/local/lib/ruby/gems/2.4.0/specifications/colorator-1.1.0.gemspec
Using ffi 1.9.18
0:  ffi (1.9.18) from /usr/local/lib/ruby/gems/2.4.0/specifications/ffi-1.9.18.gemspec
Using forwardable-extended 2.6.0
0:  forwardable-extended (2.6.0) from /usr/local/lib/ruby/gems/2.4.0/specifications/forwardable-extended-2.6.0.gemspec
Using rb-fsevent 0.10.2
0:  rb-fsevent (0.10.2) from /usr/local/lib/ruby/gems/2.4.0/specifications/rb-fsevent-0.10.2.gemspec
Using rb-inotify 0.9.10
0:  rb-inotify (0.9.10) from /usr/local/lib/ruby/gems/2.4.0/specifications/rb-inotify-0.9.10.gemspec
Using sass-listen 4.0.0
0:  sass-listen (4.0.0) from /usr/local/lib/ruby/gems/2.4.0/specifications/sass-listen-4.0.0.gemspec
Using sass 3.5.4
0:  sass (3.5.4) from /usr/local/lib/ruby/gems/2.4.0/specifications/sass-3.5.4.gemspec
Using jekyll-sass-converter 1.5.1
0:  jekyll-sass-converter (1.5.1) from /usr/local/lib/ruby/gems/2.4.0/specifications/jekyll-sass-converter-1.5.1.gemspec
Using ruby_dep 1.5.0
0:  ruby_dep (1.5.0) from /usr/local/lib/ruby/gems/2.4.0/specifications/ruby_dep-1.5.0.gemspec
Using listen 3.1.5
0:  listen (3.1.5) from /usr/local/lib/ruby/gems/2.4.0/specifications/listen-3.1.5.gemspec
Using jekyll-watch 1.5.1
0:  jekyll-watch (1.5.1) from /usr/local/lib/ruby/gems/2.4.0/specifications/jekyll-watch-1.5.1.gemspec
Using kramdown 1.16.2
0:  kramdown (1.16.2) from /usr/local/lib/ruby/gems/2.4.0/specifications/kramdown-1.16.2.gemspec
Using liquid 4.0.0
0:  liquid (4.0.0) from /usr/local/lib/ruby/gems/2.4.0/specifications/liquid-4.0.0.gemspec
Using mercenary 0.3.6
0:  mercenary (0.3.6) from /usr/local/lib/ruby/gems/2.4.0/specifications/mercenary-0.3.6.gemspec
Using pathutil 0.16.1
0:  pathutil (0.16.1) from /usr/local/lib/ruby/gems/2.4.0/specifications/pathutil-0.16.1.gemspec
Using rouge 2.2.1
0:  rouge (2.2.1) from /usr/local/lib/ruby/gems/2.4.0/specifications/rouge-2.2.1.gemspec
Using safe_yaml 1.0.4
0:  safe_yaml (1.0.4) from /usr/local/lib/ruby/gems/2.4.0/specifications/safe_yaml-1.0.4.gemspec
Using jekyll 3.6.2
0:  jekyll (3.6.2) from /usr/local/lib/ruby/gems/2.4.0/specifications/jekyll-3.6.2.gemspec
Fetching jekyll-seo-tag 2.4.0
Installing jekyll-seo-tag 2.4.0
0:  jekyll-seo-tag (2.4.0) from /usr/local/lib/ruby/gems/2.4.0/specifications/jekyll-seo-tag-2.4.0.gemspec
Using jekyll-theme-tactile 0.1.0 from source at `.`
0:  jekyll-theme-tactile (0.1.0) from support/jekyll/tactile/jekyll-theme-tactile.gemspec
Bundle complete! 1 Gemfile dependency, 23 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```


```bash
$ bundle exec jekyll serve
Configuration file: support/jekyll/tactile/_config.yml
            Source: support/jekyll/tactile
       Destination: support/jekyll/tactile/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.408 seconds.
 Auto-regeneration: enabled for 'support/jekyll/tactile'
    Server address: http://127.0.0.1:4000
  Server running... press ctrl-c to stop.
[2017-12-26 16:29:40] ERROR `/assets/main.css' not found.
```

**Comment by CarlasHub** [comment]
I have the same issue !
